version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
  backend:
    build: ./backend
    env_file: backend/.env.example
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
